# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Types/ComplexPolygon.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Types/ComplexPolygon.proto',
  package='QikkDB.Types',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aTypes/ComplexPolygon.proto\x12\x0cQikkDB.Types\"9\n\x0e\x43omplexPolygon\x12\'\n\x08polygons\x18\x01 \x03(\x0b\x32\x15.QikkDB.Types.Polygon\"4\n\x07Polygon\x12)\n\tgeoPoints\x18\x01 \x03(\x0b\x32\x16.QikkDB.Types.GeoPoint\"/\n\x08GeoPoint\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\x62\x06proto3'
)




_COMPLEXPOLYGON = _descriptor.Descriptor(
  name='ComplexPolygon',
  full_name='QikkDB.Types.ComplexPolygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='polygons', full_name='QikkDB.Types.ComplexPolygon.polygons', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=101,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='QikkDB.Types.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='geoPoints', full_name='QikkDB.Types.Polygon.geoPoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=155,
)


_GEOPOINT = _descriptor.Descriptor(
  name='GeoPoint',
  full_name='QikkDB.Types.GeoPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='QikkDB.Types.GeoPoint.latitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='QikkDB.Types.GeoPoint.longitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=204,
)

_COMPLEXPOLYGON.fields_by_name['polygons'].message_type = _POLYGON
_POLYGON.fields_by_name['geoPoints'].message_type = _GEOPOINT
DESCRIPTOR.message_types_by_name['ComplexPolygon'] = _COMPLEXPOLYGON
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['GeoPoint'] = _GEOPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComplexPolygon = _reflection.GeneratedProtocolMessageType('ComplexPolygon', (_message.Message,), {
  'DESCRIPTOR' : _COMPLEXPOLYGON,
  '__module__' : 'Types.ComplexPolygon_pb2'
  # @@protoc_insertion_point(class_scope:QikkDB.Types.ComplexPolygon)
  })
_sym_db.RegisterMessage(ComplexPolygon)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), {
  'DESCRIPTOR' : _POLYGON,
  '__module__' : 'Types.ComplexPolygon_pb2'
  # @@protoc_insertion_point(class_scope:QikkDB.Types.Polygon)
  })
_sym_db.RegisterMessage(Polygon)

GeoPoint = _reflection.GeneratedProtocolMessageType('GeoPoint', (_message.Message,), {
  'DESCRIPTOR' : _GEOPOINT,
  '__module__' : 'Types.ComplexPolygon_pb2'
  # @@protoc_insertion_point(class_scope:QikkDB.Types.GeoPoint)
  })
_sym_db.RegisterMessage(GeoPoint)


# @@protoc_insertion_point(module_scope)
