# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message/BulkImportMessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Message import CSVImportMessage_pb2 as Message_dot_CSVImportMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Message/BulkImportMessage.proto',
  package='QikkDB.NetworkClient.Message',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fMessage/BulkImportMessage.proto\x12\x1cQikkDB.NetworkClient.Message\x1a\x1eMessage/CSVImportMessage.proto\"\xb2\x01\n\x11\x42ulkImportMessage\x12\x11\n\tTableName\x18\x01 \x01(\t\x12\x12\n\nColumnName\x18\x02 \x01(\t\x12:\n\nColumnType\x18\x03 \x01(\x0e\x32&.QikkDB.NetworkClient.Message.DataType\x12\x11\n\tElemCount\x18\x04 \x01(\x05\x12\x13\n\x0bnullMaskLen\x18\x05 \x01(\x05\x12\x12\n\ndataLength\x18\x06 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[Message_dot_CSVImportMessage__pb2.DESCRIPTOR,])




_BULKIMPORTMESSAGE = _descriptor.Descriptor(
  name='BulkImportMessage',
  full_name='QikkDB.NetworkClient.Message.BulkImportMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='TableName', full_name='QikkDB.NetworkClient.Message.BulkImportMessage.TableName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ColumnName', full_name='QikkDB.NetworkClient.Message.BulkImportMessage.ColumnName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ColumnType', full_name='QikkDB.NetworkClient.Message.BulkImportMessage.ColumnType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ElemCount', full_name='QikkDB.NetworkClient.Message.BulkImportMessage.ElemCount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nullMaskLen', full_name='QikkDB.NetworkClient.Message.BulkImportMessage.nullMaskLen', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataLength', full_name='QikkDB.NetworkClient.Message.BulkImportMessage.dataLength', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=276,
)

_BULKIMPORTMESSAGE.fields_by_name['ColumnType'].enum_type = Message_dot_CSVImportMessage__pb2._DATATYPE
DESCRIPTOR.message_types_by_name['BulkImportMessage'] = _BULKIMPORTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BulkImportMessage = _reflection.GeneratedProtocolMessageType('BulkImportMessage', (_message.Message,), {
  'DESCRIPTOR' : _BULKIMPORTMESSAGE,
  '__module__' : 'Message.BulkImportMessage_pb2'
  # @@protoc_insertion_point(class_scope:QikkDB.NetworkClient.Message.BulkImportMessage)
  })
_sym_db.RegisterMessage(BulkImportMessage)


# @@protoc_insertion_point(module_scope)
